{
  "namespace": "hellnet.events",
  "type": "record",
  "name": "hellnet_order_created",
  "doc": "Emitted when an order is created",
  "fields": [
    { "name": "orderId", "type": "string", "doc": "UUID of the order" },
    { "name": "customerId", "type": "string" },
    { "name": "amount", "type": "double" },
    { "name": "currency", "type": "string", "default": "BRL" },
    { "name": "items", "type": { "type": "array", "items": {
      "type": "record", "name": "OrderItem", "fields": [
        { "name": "productId", "type": "string" },
        { "name": "quantity", "type": "int" }
      ]
    }}}
  ]
}
