name: validate-schema-pr
on:
  pull_request:
    paths:
      - "schemas/**"

jobs:
  validate:
    runs-on: arc-runner
    steps:
      - uses: actions/checkout@v4

      - name: Validate all schemas
        run: |
          chmod +x scripts/validate.sh
          ./scripts/validate.sh schemas
